# server handler config
version: 1.0
services:
  - repo-name: paisen01/read.news
    handler: "handler" 
    script: "read.news.sh"
    args: "-args"
  - repo-name: paisen02/read.news
    handler: "cmd2" 
